### ISSUE TITLE
v1.1 added non-free dependencies and trackers

### ISSUE THREAD

**Issue by IzzySoft** [pakka-papad/Zen#12]
I just received the update to v1.1, and while the initial version was "pure FOSS" and privacy-friendly, this is no longer true:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

5 offenders.
```

Your release notes do not mention this, so I wonder if those modules were added intentionally – or just slipped in as dependency of some other library? Could you please remove those again – or at least provide a build flavor without? The app listing looks a bit scary now, too:

![image](https://user-images.githubusercontent.com/6781438/226737706-229572d8-f8a9-4b0e-ab02-10e8533447f8.png)

**Comment by pakka-papad** [comment]
v1.1 uses Firebase Crashlytics as a dependency. It is added to report crash and anr logs automatically but the **user can opt out of automatic reporting** within the app's settings. Refer to privacy policy for more information regarding this.

**Comment by IzzySoft** [comment]
So using an [alternative, non-proprietary solution](https://gitlab.com/-/snippets/1896503#acceptable-analytics) for that is no option – it must be proprietary Crashlytics? Note that with proprietary libs you always have to trust they do nothing you do not want: there's no source to check against. Especially when such a lib comes from a company known to live on our data, I'm very sceptical. That has less to do with trust on you, but more with trust on them; wouldn't be the first time they're caught with their pants down (remember their collection of location data despite the user having opted out?). Your privacy policy cannot honestly promise what Google won't do as you don't have control over that part.

Further, opt-out does not help much here. Tracking already starts before you can do so. Tracking must always be strictly opt-in (optionally asked for at first start if you don't want to wait for users to discover that toggle).

**Comment by pakka-papad** [comment]
Thanks for sharing the alternatives. I will explore the possible solutions and try to remove firebase in the next versions of the app.

**Comment by IzzySoft** [comment]
Are there any news on this?

**Comment by IzzySoft** [comment]
@pakka-papad you're still working on the app?

**Comment by pakka-papad** [comment]
Yes

**Comment by IzzySoft** [comment]
Good to know, thanks! Any ETA for the above issue? You wrote about removing Firebase back in March. Not pressing, just want to know for orientation.

**Comment by IzzySoft** [comment]
@pakka-papad The issue just popped up again on my end. I see some new commits here, but none addressing the issue. Any ETA when this will be done? It's already 8 months now since you wrote to address this.

**Comment by atomspring** [comment]
Nah this lazy clown doesn't care. Just move on, the app isn't super stable anyway which is why he's so worried about anr's.

**Comment by IzzySoft** [comment]
@pakka-papad just wondering: two times you promised to address this, and now you close it as "not planned" without any explanation even? That's disappointing, and raises the question of how much one can trust you mean what you say.

So as you plan to keep this as-is, maybe you mention it with your "tech stack" section in the readme? I mean, if even Hilt and Timber are worth a mention there, Crashlytics and Firebase should be, too. Or do you rather prefer keeping these out-of-view? Then maybe I should better remove your app from my repo, which clearly points that out:

![image](https://github.com/pakka-papad/Zen/assets/6781438/4c66eba6-80fd-4759-a90e-5c2c8644ca75)

Draws quite a nice picture with the AntiFeatures block longer than the app description :see_no_evil:

**Comment by pakka-papad** [comment]
Removing crashlytics won't be done anytime soon. You may go and remove the app from your repo.

**Comment by IzzySoft** [comment]
OK, done then, effective with the next sync around 7 pm UTC. All the best for future development – and should you one day decide to tackle this, just give me a ping here and I can check whether to re-establish your app in my repo.
