### ISSUE TITLE
Issue with scanning music

### ISSUE THREAD

**Issue by hibonox705** [pakka-papad/Zen#17]
Hi there,
I just installed your app latest version using the APK and I just get stuck at the storage scan screen. I don't know if I have too many songs so it takes a while or if it's a bug but I get stuck here
![Screenshot_2023-12-05-09-56-14-635_com github pakka_papad](https://github.com/pakka-papad/Zen/assets/116116660/60606a7d-bdc7-4cf6-a5f6-ce203cdee9bb)

I'm a MIUI14 user, so I don't know if that influence also

**Comment by pakka-papad** [comment]
Thanks for reporting the issue. For how long is the screen stuck here?

**Comment by hibonox705** [comment]
> Thanks for reporting the issue. For how long is the screen stuck here?

No problem.
It literally took 10 minutes to scan everything (I used a stopwatch to know)

**Comment by hibonox705** [comment]
> Thanks for the feedback. It is the metadata extraction that is taking this long. Due to the large number of songs, it feels like the app is not responding at all. I will try to add some kind of indicator to show that the app is still running.

No problem and yeah that's a great idea
Thanks for responding so quickly, it's always awesome when developers interact with the community to get feedback and everything.
Do you want me to close the issue or let it open until it may be implemented?

**Comment by hibonox705** [comment]
Hi,
Just wanted to say that you implemented the indication that it's scanning and everything is working fine so I'm closing the issue.
Thanks for doing so and creating a music player like this
