### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [pakka-papad/Zen#5]
Please support the Themed Icon.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

![Screenshot_2023-02-20-23-37-34-143_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/220191106-031e2ea0-480e-4233-a21c-9c9e02090003.jpg)

Thanks.

**Comment by pakka-papad** [comment]
It will be released in next version

**Comment by xmha97** [comment]
Thank you 🙏
