### ISSUE TITLE
Swipe down to back

### ISSUE THREAD

**Issue by xmha97** [pakka-papad/Zen#6]
Please add the feature below:
- Swipe down to back:
![Screenshot_2023-02-20-23-46-19-016_com.github.pakka_papad.jpg](https://user-images.githubusercontent.com/23485114/220191597-fa115a00-009f-42f5-a752-d1a5e2867475.jpg)
After the swipe down:
![Screenshot_2023-02-20-23-49-04-203_com.github.pakka_papad.jpg](https://user-images.githubusercontent.com/23485114/220191831-71106d84-cbe7-4ce7-9318-88dc751b724e.jpg)

**Comment by pakka-papad** [comment]
Next version of app will have the bottom mini player to be swipeable. 
OnSwipeUp on bottom mini player: move to full screen player. 
OnSwipeDown in full screen player: move back to home screen.

**Comment by xmha97** [comment]
Thanks 🙏
