### ISSUE TITLE
Feature Request: Add Scrobbling 

### ISSUE THREAD

**Issue by rozari0** [pakka-papad/Zen#9]
Hello, I found Zen music from Fdroid. This app looks cool, but Pano Scrobbler can't Scrobble from this app. This has something to do with notifications.
If possible, please add this feature.

**Comment by pakka-papad** [comment]
Please share the f-droid link

**Comment by rozari0** [comment]
> Please share the f-droid link

https://apt.izzysoft.de/fdroid/index/apk/com.github.pakka_papad
